[package]
name = "test_client"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
tungstenite = "0.11.0"
color-eyre = "0.5.8"
ureq = { version = "1.5", features = ["json"] }
