[package]
name = "test_client"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
# https://github.com/snapview/tungstenite-rs/pull/166
tungstenite = { version = "0.13.0", git = "https://github.com/dnaka91/tungstenite-rs", branch = "rustls", features = ["use-rustls"] }
color-eyre = "0.5.8"
ureq = { version = "1.5", features = ["json"] }
