name: Release

on:
  release:
    types: [created]

env:
  APP_NAME: notify_push

jobs:
  release-binaries:
    name: Build release binaries
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - i686-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - aarch64-unknown-linux-musl
          - x86_64-unknown-freebsd

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: setup cross
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall --no-confirm cross
      - name: build
        run: |
          cross build --release --target ${{ matrix.target }}
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/notify_push
          asset_name: notify_push-${{ matrix.target }}
          tag: ${{ github.ref }}

  build-test-client:
    name: Build test client
    runs-on: ubuntu-20.04

    steps:
      - name: musl-tools
        run: |
          sudo apt-get install musl-tools
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl
      - run: cargo build --release --target x86_64-unknown-linux-musl
        working-directory: ./test_client
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-unknown-linux-musl/release/test_client
          asset_name: test_client
          tag: ${{ github.ref }}
