name: Rust CI

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - stable*

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl
      - uses: Swatinem/rust-cache@v2.2.0
      - uses: actions-rs/cargo@v1
        with:
          command: check

  build:
    name: Build release
    runs-on: ubuntu-latest
    needs: check
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - i686-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - aarch64-unknown-linux-musl
          - x86_64-unknown-freebsd

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2.2.0
        with:
          key: ${{ matrix.target }}
      - name: setup cross
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall --no-confirm cross
      - name: build
        run: |
          cross build --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v3
        with:
          name: notify_push-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/notify_push

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: check

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl
      - uses: Swatinem/rust-cache@v2.2.0
      - uses: actions-rs/cargo@v1
        with:
          command: test

  build-test-client:
    name: Build test client
    runs-on: ubuntu-latest

    steps:
      - name: musl-tools
        run: |
          sudo apt-get install musl-tools
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl
      - uses: Swatinem/rust-cache@v2.2.0
      - run: cargo build --release --target x86_64-unknown-linux-musl
        working-directory: ./test_client
      - uses: actions/upload-artifact@v3
        with:
          name: test_client
          path: target/x86_64-unknown-linux-musl/release/test_client

  msrv:
    name: Check MSRV
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.64.0
        with:
          targets: x86_64-unknown-linux-musl
      - uses: Swatinem/rust-cache@v2.2.0
      - uses: actions-rs/cargo@v1
        with:
          command: check
